plugins:
- jekyll-remote-theme
remote_theme: pages-themes/cayman@v0.2.0
markdown: kramdown
title: Group 37 - BdSL
description: Charles (Charlie) Bauer, Divyam Gupta, Jui-Tse (Ray) Hung, Prithvi Khosla, Geonhui (Aiden) Lee
